language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
env:
  - PIP_USE_MIRRORS=true
# # command to run tests
before_install:
 - "pip install -U pytest"
script: "python setup.py pytest"
